export interface GalleryItem {
  id: string;
  src: string;
  title: string;
  category: "stay" | "evenings" | "winter" | "around-kalam";
  categoryLabel: string;
  locationLabel: "Property" | "Explore Kalam";
  alt: string;
  aspect?: "tall" | "wide" | "square";
}

export const galleryCategories = [
  { id: "all", label: "All Moments" },
  { id: "stay", label: "The Stay" },
  { id: "evenings", label: "Evenings" },
  { id: "winter", label: "Winter Season" },
  { id: "around-kalam", label: "Around Kalam" },
];

export const galleryItems: GalleryItem[] = [
  // --- THE STAY / PROPERTY ---
  {
    id: "g-03",
    src: "/assets/secret-garden/03-cottage-night-exterior.jpg",
    title: "Cottage Under Night Sky",
    category: "stay",
    categoryLabel: "The Stay",
    locationLabel: "Property",
    alt: "Warm wooden cottage lit up at night under pine trees",
    aspect: "wide",
  },
  {
    id: "g-08",
    src: "/assets/secret-garden/08-cottage-rainy-day-exterior.jpg",
    title: "Rainy Mountain Afternoon",
    category: "stay",
    categoryLabel: "The Stay",
    locationLabel: "Property",
    alt: "Retreat cottage exterior on a serene rainy day in Kalam",
    aspect: "wide",
  },
  {
    id: "g-22",
    src: "/assets/secret-garden/22-secret-garden-outdoor-lounge-seating.png",
    title: "Garden Lounge & Lawn",
    category: "stay",
    categoryLabel: "The Stay",
    locationLabel: "Property",
    alt: "Outdoor lounge seating surrounded by stone wall and garden greenery",
    aspect: "wide",
  },

  // --- EVENINGS ---
  {
    id: "g-04",
    src: "/assets/secret-garden/04-veranda-sofa-night.jpg",
    title: "Veranda Evening Glow",
    category: "evenings",
    categoryLabel: "Evenings",
    locationLabel: "Property",
    alt: "Warm sofa seating on the cottage veranda illuminated by ambient light",
    aspect: "tall",
  },
  {
    id: "g-05",
    src: "/assets/secret-garden/05-veranda-passage-night.jpg",
    title: "Passage & Warm Amber Light",
    category: "evenings",
    categoryLabel: "Evenings",
    locationLabel: "Property",
    alt: "Wooden veranda walkway under warm string lights at dusk",
    aspect: "tall",
  },
  {
    id: "g-10",
    src: "/assets/secret-garden/10-rope-bulbs-closeup.jpg",
    title: "Warm Rope Bulbs Detail",
    category: "evenings",
    categoryLabel: "Evenings",
    locationLabel: "Property",
    alt: "Close up of glowing warm Edison rope light bulbs",
    aspect: "square",
  },
  {
    id: "g-09",
    src: "/assets/secret-garden/09-covered-driveway-view.jpg",
    title: "Driveway Passage at Dusk",
    category: "evenings",
    categoryLabel: "Evenings",
    locationLabel: "Property",
    alt: "Covered stone driveway illuminated with warm cottage lighting",
    aspect: "wide",
  },

  // --- WINTER SEASON ---
  {
    id: "g-23",
    src: "/assets/secret-garden/23-secret-garden-snowy-garden-seating.png",
    title: "Snowy Garden Seating",
    category: "winter",
    categoryLabel: "Winter Season",
    locationLabel: "Property",
    alt: "Snow-draped garden furniture in quiet winter solitude",
    aspect: "wide",
  },
  {
    id: "g-24",
    src: "/assets/secret-garden/24-secret-garden-winter-entrance-road.png",
    title: "Winter Entrance Pathway",
    category: "winter",
    categoryLabel: "Winter Season",
    locationLabel: "Property",
    alt: "Snowy driveway entrance into Secret Garden Kalam",
    aspect: "wide",
  },
  {
    id: "g-25",
    src: "/assets/secret-garden/25-secret-garden-cottage-winter-exterior.png",
    title: "Winter Cottage Horizon",
    category: "winter",
    categoryLabel: "Winter Season",
    locationLabel: "Property",
    alt: "Cottage exterior nestled in fresh winter snow",
    aspect: "wide",
  },

  // --- AROUND KALAM (DESTINATION) ---
  {
    id: "g-11",
    src: "/assets/secret-garden/11-kalam-mountain-slope-aerial.jpg",
    title: "Into the Mountains",
    category: "around-kalam",
    categoryLabel: "Around Kalam",
    locationLabel: "Explore Kalam",
    alt: "Aerial vista of Kalam mountain slopes and deep forest valley",
    aspect: "wide",
  },
  {
    id: "g-12",
    src: "/assets/secret-garden/12-kalam-river-wooden-bridge.jpg",
    title: "Across Quiet Waters",
    category: "around-kalam",
    categoryLabel: "Around Kalam",
    locationLabel: "Explore Kalam",
    alt: "Wooden bridge crossing the rushing glacial river of Kalam",
    aspect: "tall",
  },
  {
    id: "g-13",
    src: "/assets/secret-garden/13-kalam-snowy-mountain-valley.jpg",
    title: "Under Snow-Capped Peaks",
    category: "around-kalam",
    categoryLabel: "Around Kalam",
    locationLabel: "Explore Kalam",
    alt: "Snow covered alpine mountain ridge towering over Kalam valley",
    aspect: "wide",
  },
  {
    id: "g-14",
    src: "/assets/secret-garden/14-kalam-lake-tall-pines.jpg",
    title: "Along Alpine Lakes",
    category: "around-kalam",
    categoryLabel: "Around Kalam",
    locationLabel: "Explore Kalam",
    alt: "Tall pine trees bordering an emerald mountain lake in Kalam",
    aspect: "tall",
  },
  {
    id: "g-15",
    src: "/assets/secret-garden/15-kalam-valley-lake-wide.jpg",
    title: "Through the Valley",
    category: "around-kalam",
    categoryLabel: "Around Kalam",
    locationLabel: "Explore Kalam",
    alt: "Wide panoramic view of Swat valley lake and surrounding peaks",
    aspect: "wide",
  },
  {
    id: "g-16",
    src: "/assets/secret-garden/16-kalam-reflective-water-snow-peak.jpg",
    title: "Where Water Holds the Sky",
    category: "around-kalam",
    categoryLabel: "Around Kalam",
    locationLabel: "Explore Kalam",
    alt: "Clear reflection of snowy mountain peak in tranquil lake water",
    aspect: "wide",
  },
  {
    id: "g-17",
    src: "/assets/secret-garden/17-kalam-misty-meadow-cow.jpg",
    title: "Life Moves Slowly Here",
    category: "around-kalam",
    categoryLabel: "Around Kalam",
    locationLabel: "Explore Kalam",
    alt: "Misty mountain meadow with cows grazing peacefully",
    aspect: "square",
  },
  {
    id: "g-18",
    src: "/assets/secret-garden/18-kalam-forest-river.jpg",
    title: "Following the River",
    category: "around-kalam",
    categoryLabel: "Around Kalam",
    locationLabel: "Explore Kalam",
    alt: "Clear mountain stream cutting through dense pine forest",
    aspect: "wide",
  },
  {
    id: "g-20",
    src: "/assets/secret-garden/20-kalam-waterfall-cliff.jpg",
    title: "Beneath the Falls",
    category: "around-kalam",
    categoryLabel: "Around Kalam",
    locationLabel: "Explore Kalam",
    alt: "Majestic waterfall cascading over rocky alpine cliff",
    aspect: "tall",
  },
  {
    id: "g-21",
    src: "/assets/secret-garden/21-kalam-green-lake-cows.jpg",
    title: "At the Edge of Green",
    category: "around-kalam",
    categoryLabel: "Around Kalam",
    locationLabel: "Explore Kalam",
    alt: "Emerald lake shore in Kalam surrounded by lush mountain pastures",
    aspect: "wide",
  },
];
